apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - image: 58910810/capstone-project:latest
        imagePullPolicy: Always
        name: capstone-app
        ports:
        - containerPort: 3000
          protocol: TCP